// source: koinos/rpc/contract_meta_store/contract_meta_store_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.koinos.rpc.contract_meta_store.contract_meta_store_request');
goog.provide('proto.koinos.rpc.contract_meta_store.contract_meta_store_request.RequestCase');
goog.provide('proto.koinos.rpc.contract_meta_store.contract_meta_store_response');
goog.provide('proto.koinos.rpc.contract_meta_store.contract_meta_store_response.ResponseCase');
goog.provide('proto.koinos.rpc.contract_meta_store.get_contract_meta_request');
goog.provide('proto.koinos.rpc.contract_meta_store.get_contract_meta_response');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.koinos.contract_meta_store.contract_meta_item');
goog.require('proto.koinos.rpc.error_response');
goog.require('proto.koinos.rpc.reserved_rpc');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.koinos.rpc.contract_meta_store.get_contract_meta_request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.rpc.contract_meta_store.get_contract_meta_request.displayName = 'proto.koinos.rpc.contract_meta_store.get_contract_meta_request';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.koinos.rpc.contract_meta_store.get_contract_meta_response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.rpc.contract_meta_store.get_contract_meta_response.displayName = 'proto.koinos.rpc.contract_meta_store.get_contract_meta_response';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.koinos.rpc.contract_meta_store.contract_meta_store_request.oneofGroups_);
};
goog.inherits(proto.koinos.rpc.contract_meta_store.contract_meta_store_request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.rpc.contract_meta_store.contract_meta_store_request.displayName = 'proto.koinos.rpc.contract_meta_store.contract_meta_store_request';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.koinos.rpc.contract_meta_store.contract_meta_store_response.oneofGroups_);
};
goog.inherits(proto.koinos.rpc.contract_meta_store.contract_meta_store_response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.rpc.contract_meta_store.contract_meta_store_response.displayName = 'proto.koinos.rpc.contract_meta_store.contract_meta_store_response';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.rpc.contract_meta_store.get_contract_meta_request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.rpc.contract_meta_store.get_contract_meta_request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.toObject = function(includeInstance, msg) {
  var f, obj = {
    contractId: msg.getContractId_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.rpc.contract_meta_store.get_contract_meta_request}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.rpc.contract_meta_store.get_contract_meta_request;
  return proto.koinos.rpc.contract_meta_store.get_contract_meta_request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.rpc.contract_meta_store.get_contract_meta_request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.rpc.contract_meta_store.get_contract_meta_request}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setContractId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.rpc.contract_meta_store.get_contract_meta_request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.rpc.contract_meta_store.get_contract_meta_request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContractId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes contract_id = 1;
 * @return {!(string|Uint8Array)}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.prototype.getContractId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes contract_id = 1;
 * This is a type-conversion wrapper around `getContractId()`
 * @return {string}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.prototype.getContractId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getContractId()));
};


/**
 * optional bytes contract_id = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getContractId()`
 * @return {!Uint8Array}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.prototype.getContractId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getContractId()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.koinos.rpc.contract_meta_store.get_contract_meta_request} returns this
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_request.prototype.setContractId = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.rpc.contract_meta_store.get_contract_meta_response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.rpc.contract_meta_store.get_contract_meta_response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.toObject = function(includeInstance, msg) {
  var f, obj = {
    meta: (f = msg.getMeta()) && proto.koinos.contract_meta_store.contract_meta_item.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.rpc.contract_meta_store.get_contract_meta_response}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.rpc.contract_meta_store.get_contract_meta_response;
  return proto.koinos.rpc.contract_meta_store.get_contract_meta_response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.rpc.contract_meta_store.get_contract_meta_response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.rpc.contract_meta_store.get_contract_meta_response}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.koinos.contract_meta_store.contract_meta_item;
      reader.readMessage(value,proto.koinos.contract_meta_store.contract_meta_item.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.rpc.contract_meta_store.get_contract_meta_response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.rpc.contract_meta_store.get_contract_meta_response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.koinos.contract_meta_store.contract_meta_item.serializeBinaryToWriter
    );
  }
};


/**
 * optional koinos.contract_meta_store.contract_meta_item meta = 1;
 * @return {?proto.koinos.contract_meta_store.contract_meta_item}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.prototype.getMeta = function() {
  return /** @type{?proto.koinos.contract_meta_store.contract_meta_item} */ (
    jspb.Message.getWrapperField(this, proto.koinos.contract_meta_store.contract_meta_item, 1));
};


/**
 * @param {?proto.koinos.contract_meta_store.contract_meta_item|undefined} value
 * @return {!proto.koinos.rpc.contract_meta_store.get_contract_meta_response} returns this
*/
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.contract_meta_store.get_contract_meta_response} returns this
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.contract_meta_store.get_contract_meta_response.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.RequestCase = {
  REQUEST_NOT_SET: 0,
  RESERVED: 1,
  GET_CONTRACT_META: 2
};

/**
 * @return {proto.koinos.rpc.contract_meta_store.contract_meta_store_request.RequestCase}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.getRequestCase = function() {
  return /** @type {proto.koinos.rpc.contract_meta_store.contract_meta_store_request.RequestCase} */(jspb.Message.computeOneofCase(this, proto.koinos.rpc.contract_meta_store.contract_meta_store_request.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.rpc.contract_meta_store.contract_meta_store_request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.rpc.contract_meta_store.contract_meta_store_request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.toObject = function(includeInstance, msg) {
  var f, obj = {
    reserved: (f = msg.getReserved()) && proto.koinos.rpc.reserved_rpc.toObject(includeInstance, f),
    getContractMeta: (f = msg.getGetContractMeta()) && proto.koinos.rpc.contract_meta_store.get_contract_meta_request.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_request}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.rpc.contract_meta_store.contract_meta_store_request;
  return proto.koinos.rpc.contract_meta_store.contract_meta_store_request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.rpc.contract_meta_store.contract_meta_store_request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_request}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.koinos.rpc.reserved_rpc;
      reader.readMessage(value,proto.koinos.rpc.reserved_rpc.deserializeBinaryFromReader);
      msg.setReserved(value);
      break;
    case 2:
      var value = new proto.koinos.rpc.contract_meta_store.get_contract_meta_request;
      reader.readMessage(value,proto.koinos.rpc.contract_meta_store.get_contract_meta_request.deserializeBinaryFromReader);
      msg.setGetContractMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.rpc.contract_meta_store.contract_meta_store_request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.rpc.contract_meta_store.contract_meta_store_request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReserved();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.koinos.rpc.reserved_rpc.serializeBinaryToWriter
    );
  }
  f = message.getGetContractMeta();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.koinos.rpc.contract_meta_store.get_contract_meta_request.serializeBinaryToWriter
    );
  }
};


/**
 * optional koinos.rpc.reserved_rpc reserved = 1;
 * @return {?proto.koinos.rpc.reserved_rpc}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.getReserved = function() {
  return /** @type{?proto.koinos.rpc.reserved_rpc} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.reserved_rpc, 1));
};


/**
 * @param {?proto.koinos.rpc.reserved_rpc|undefined} value
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_request} returns this
*/
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.setReserved = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.koinos.rpc.contract_meta_store.contract_meta_store_request.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_request} returns this
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.clearReserved = function() {
  return this.setReserved(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.hasReserved = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional get_contract_meta_request get_contract_meta = 2;
 * @return {?proto.koinos.rpc.contract_meta_store.get_contract_meta_request}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.getGetContractMeta = function() {
  return /** @type{?proto.koinos.rpc.contract_meta_store.get_contract_meta_request} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.contract_meta_store.get_contract_meta_request, 2));
};


/**
 * @param {?proto.koinos.rpc.contract_meta_store.get_contract_meta_request|undefined} value
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_request} returns this
*/
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.setGetContractMeta = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.koinos.rpc.contract_meta_store.contract_meta_store_request.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_request} returns this
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.clearGetContractMeta = function() {
  return this.setGetContractMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_request.prototype.hasGetContractMeta = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  RESERVED: 1,
  ERROR: 2,
  GET_CONTRACT_META: 3
};

/**
 * @return {proto.koinos.rpc.contract_meta_store.contract_meta_store_response.ResponseCase}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.getResponseCase = function() {
  return /** @type {proto.koinos.rpc.contract_meta_store.contract_meta_store_response.ResponseCase} */(jspb.Message.computeOneofCase(this, proto.koinos.rpc.contract_meta_store.contract_meta_store_response.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.rpc.contract_meta_store.contract_meta_store_response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.toObject = function(includeInstance, msg) {
  var f, obj = {
    reserved: (f = msg.getReserved()) && proto.koinos.rpc.reserved_rpc.toObject(includeInstance, f),
    error: (f = msg.getError()) && proto.koinos.rpc.error_response.toObject(includeInstance, f),
    getContractMeta: (f = msg.getGetContractMeta()) && proto.koinos.rpc.contract_meta_store.get_contract_meta_response.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.rpc.contract_meta_store.contract_meta_store_response;
  return proto.koinos.rpc.contract_meta_store.contract_meta_store_response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.koinos.rpc.reserved_rpc;
      reader.readMessage(value,proto.koinos.rpc.reserved_rpc.deserializeBinaryFromReader);
      msg.setReserved(value);
      break;
    case 2:
      var value = new proto.koinos.rpc.error_response;
      reader.readMessage(value,proto.koinos.rpc.error_response.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 3:
      var value = new proto.koinos.rpc.contract_meta_store.get_contract_meta_response;
      reader.readMessage(value,proto.koinos.rpc.contract_meta_store.get_contract_meta_response.deserializeBinaryFromReader);
      msg.setGetContractMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.rpc.contract_meta_store.contract_meta_store_response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReserved();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.koinos.rpc.reserved_rpc.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.koinos.rpc.error_response.serializeBinaryToWriter
    );
  }
  f = message.getGetContractMeta();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.koinos.rpc.contract_meta_store.get_contract_meta_response.serializeBinaryToWriter
    );
  }
};


/**
 * optional koinos.rpc.reserved_rpc reserved = 1;
 * @return {?proto.koinos.rpc.reserved_rpc}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.getReserved = function() {
  return /** @type{?proto.koinos.rpc.reserved_rpc} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.reserved_rpc, 1));
};


/**
 * @param {?proto.koinos.rpc.reserved_rpc|undefined} value
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response} returns this
*/
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.setReserved = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.koinos.rpc.contract_meta_store.contract_meta_store_response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response} returns this
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.clearReserved = function() {
  return this.setReserved(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.hasReserved = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional koinos.rpc.error_response error = 2;
 * @return {?proto.koinos.rpc.error_response}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.getError = function() {
  return /** @type{?proto.koinos.rpc.error_response} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.error_response, 2));
};


/**
 * @param {?proto.koinos.rpc.error_response|undefined} value
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response} returns this
*/
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.setError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.koinos.rpc.contract_meta_store.contract_meta_store_response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response} returns this
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional get_contract_meta_response get_contract_meta = 3;
 * @return {?proto.koinos.rpc.contract_meta_store.get_contract_meta_response}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.getGetContractMeta = function() {
  return /** @type{?proto.koinos.rpc.contract_meta_store.get_contract_meta_response} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.contract_meta_store.get_contract_meta_response, 3));
};


/**
 * @param {?proto.koinos.rpc.contract_meta_store.get_contract_meta_response|undefined} value
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response} returns this
*/
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.setGetContractMeta = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.koinos.rpc.contract_meta_store.contract_meta_store_response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.contract_meta_store.contract_meta_store_response} returns this
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.clearGetContractMeta = function() {
  return this.setGetContractMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.contract_meta_store.contract_meta_store_response.prototype.hasGetContractMeta = function() {
  return jspb.Message.getField(this, 3) != null;
};


