// source: koinos/contracts/resources/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.koinos.contracts.resources.get_resource_markets_arguments');
goog.provide('proto.koinos.contracts.resources.get_resource_markets_result');
goog.provide('proto.koinos.contracts.resources.market');
goog.provide('proto.koinos.contracts.resources.resource_markets');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.contracts.resources.market = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.koinos.contracts.resources.market, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.contracts.resources.market.displayName = 'proto.koinos.contracts.resources.market';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.contracts.resources.resource_markets = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.koinos.contracts.resources.resource_markets, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.contracts.resources.resource_markets.displayName = 'proto.koinos.contracts.resources.resource_markets';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.contracts.resources.get_resource_markets_arguments = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.koinos.contracts.resources.get_resource_markets_arguments, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.contracts.resources.get_resource_markets_arguments.displayName = 'proto.koinos.contracts.resources.get_resource_markets_arguments';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.contracts.resources.get_resource_markets_result = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.koinos.contracts.resources.get_resource_markets_result, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.contracts.resources.get_resource_markets_result.displayName = 'proto.koinos.contracts.resources.get_resource_markets_result';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.contracts.resources.market.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.contracts.resources.market.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.contracts.resources.market} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.contracts.resources.market.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceSupply: jspb.Message.getFieldWithDefault(msg, 1, "0"),
    rcReserve: jspb.Message.getFieldWithDefault(msg, 2, "0"),
    blockBudget: jspb.Message.getFieldWithDefault(msg, 3, "0"),
    blockLimit: jspb.Message.getFieldWithDefault(msg, 4, "0")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.contracts.resources.market}
 */
proto.koinos.contracts.resources.market.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.contracts.resources.market;
  return proto.koinos.contracts.resources.market.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.contracts.resources.market} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.contracts.resources.market}
 */
proto.koinos.contracts.resources.market.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readUint64String());
      msg.setResourceSupply(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readUint64String());
      msg.setRcReserve(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readUint64String());
      msg.setBlockBudget(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readUint64String());
      msg.setBlockLimit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.contracts.resources.market.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.contracts.resources.market.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.contracts.resources.market} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.contracts.resources.market.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceSupply();
  if (parseInt(f, 10) !== 0) {
    writer.writeUint64String(
      1,
      f
    );
  }
  f = message.getRcReserve();
  if (parseInt(f, 10) !== 0) {
    writer.writeUint64String(
      2,
      f
    );
  }
  f = message.getBlockBudget();
  if (parseInt(f, 10) !== 0) {
    writer.writeUint64String(
      3,
      f
    );
  }
  f = message.getBlockLimit();
  if (parseInt(f, 10) !== 0) {
    writer.writeUint64String(
      4,
      f
    );
  }
};


/**
 * optional uint64 resource_supply = 1;
 * @return {string}
 */
proto.koinos.contracts.resources.market.prototype.getResourceSupply = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, "0"));
};


/**
 * @param {string} value
 * @return {!proto.koinos.contracts.resources.market} returns this
 */
proto.koinos.contracts.resources.market.prototype.setResourceSupply = function(value) {
  return jspb.Message.setProto3StringIntField(this, 1, value);
};


/**
 * optional uint64 rc_reserve = 2;
 * @return {string}
 */
proto.koinos.contracts.resources.market.prototype.getRcReserve = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, "0"));
};


/**
 * @param {string} value
 * @return {!proto.koinos.contracts.resources.market} returns this
 */
proto.koinos.contracts.resources.market.prototype.setRcReserve = function(value) {
  return jspb.Message.setProto3StringIntField(this, 2, value);
};


/**
 * optional uint64 block_budget = 3;
 * @return {string}
 */
proto.koinos.contracts.resources.market.prototype.getBlockBudget = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, "0"));
};


/**
 * @param {string} value
 * @return {!proto.koinos.contracts.resources.market} returns this
 */
proto.koinos.contracts.resources.market.prototype.setBlockBudget = function(value) {
  return jspb.Message.setProto3StringIntField(this, 3, value);
};


/**
 * optional uint64 block_limit = 4;
 * @return {string}
 */
proto.koinos.contracts.resources.market.prototype.getBlockLimit = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, "0"));
};


/**
 * @param {string} value
 * @return {!proto.koinos.contracts.resources.market} returns this
 */
proto.koinos.contracts.resources.market.prototype.setBlockLimit = function(value) {
  return jspb.Message.setProto3StringIntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.contracts.resources.resource_markets.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.contracts.resources.resource_markets.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.contracts.resources.resource_markets} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.contracts.resources.resource_markets.toObject = function(includeInstance, msg) {
  var f, obj = {
    diskStorage: (f = msg.getDiskStorage()) && proto.koinos.contracts.resources.market.toObject(includeInstance, f),
    networkBandwidth: (f = msg.getNetworkBandwidth()) && proto.koinos.contracts.resources.market.toObject(includeInstance, f),
    computeBandwidth: (f = msg.getComputeBandwidth()) && proto.koinos.contracts.resources.market.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.contracts.resources.resource_markets}
 */
proto.koinos.contracts.resources.resource_markets.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.contracts.resources.resource_markets;
  return proto.koinos.contracts.resources.resource_markets.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.contracts.resources.resource_markets} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.contracts.resources.resource_markets}
 */
proto.koinos.contracts.resources.resource_markets.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.koinos.contracts.resources.market;
      reader.readMessage(value,proto.koinos.contracts.resources.market.deserializeBinaryFromReader);
      msg.setDiskStorage(value);
      break;
    case 2:
      var value = new proto.koinos.contracts.resources.market;
      reader.readMessage(value,proto.koinos.contracts.resources.market.deserializeBinaryFromReader);
      msg.setNetworkBandwidth(value);
      break;
    case 3:
      var value = new proto.koinos.contracts.resources.market;
      reader.readMessage(value,proto.koinos.contracts.resources.market.deserializeBinaryFromReader);
      msg.setComputeBandwidth(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.contracts.resources.resource_markets.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.contracts.resources.resource_markets.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.contracts.resources.resource_markets} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.contracts.resources.resource_markets.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDiskStorage();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.koinos.contracts.resources.market.serializeBinaryToWriter
    );
  }
  f = message.getNetworkBandwidth();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.koinos.contracts.resources.market.serializeBinaryToWriter
    );
  }
  f = message.getComputeBandwidth();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.koinos.contracts.resources.market.serializeBinaryToWriter
    );
  }
};


/**
 * optional market disk_storage = 1;
 * @return {?proto.koinos.contracts.resources.market}
 */
proto.koinos.contracts.resources.resource_markets.prototype.getDiskStorage = function() {
  return /** @type{?proto.koinos.contracts.resources.market} */ (
    jspb.Message.getWrapperField(this, proto.koinos.contracts.resources.market, 1));
};


/**
 * @param {?proto.koinos.contracts.resources.market|undefined} value
 * @return {!proto.koinos.contracts.resources.resource_markets} returns this
*/
proto.koinos.contracts.resources.resource_markets.prototype.setDiskStorage = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.contracts.resources.resource_markets} returns this
 */
proto.koinos.contracts.resources.resource_markets.prototype.clearDiskStorage = function() {
  return this.setDiskStorage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.contracts.resources.resource_markets.prototype.hasDiskStorage = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional market network_bandwidth = 2;
 * @return {?proto.koinos.contracts.resources.market}
 */
proto.koinos.contracts.resources.resource_markets.prototype.getNetworkBandwidth = function() {
  return /** @type{?proto.koinos.contracts.resources.market} */ (
    jspb.Message.getWrapperField(this, proto.koinos.contracts.resources.market, 2));
};


/**
 * @param {?proto.koinos.contracts.resources.market|undefined} value
 * @return {!proto.koinos.contracts.resources.resource_markets} returns this
*/
proto.koinos.contracts.resources.resource_markets.prototype.setNetworkBandwidth = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.contracts.resources.resource_markets} returns this
 */
proto.koinos.contracts.resources.resource_markets.prototype.clearNetworkBandwidth = function() {
  return this.setNetworkBandwidth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.contracts.resources.resource_markets.prototype.hasNetworkBandwidth = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional market compute_bandwidth = 3;
 * @return {?proto.koinos.contracts.resources.market}
 */
proto.koinos.contracts.resources.resource_markets.prototype.getComputeBandwidth = function() {
  return /** @type{?proto.koinos.contracts.resources.market} */ (
    jspb.Message.getWrapperField(this, proto.koinos.contracts.resources.market, 3));
};


/**
 * @param {?proto.koinos.contracts.resources.market|undefined} value
 * @return {!proto.koinos.contracts.resources.resource_markets} returns this
*/
proto.koinos.contracts.resources.resource_markets.prototype.setComputeBandwidth = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.contracts.resources.resource_markets} returns this
 */
proto.koinos.contracts.resources.resource_markets.prototype.clearComputeBandwidth = function() {
  return this.setComputeBandwidth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.contracts.resources.resource_markets.prototype.hasComputeBandwidth = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.contracts.resources.get_resource_markets_arguments.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.contracts.resources.get_resource_markets_arguments.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.contracts.resources.get_resource_markets_arguments} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.contracts.resources.get_resource_markets_arguments.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.contracts.resources.get_resource_markets_arguments}
 */
proto.koinos.contracts.resources.get_resource_markets_arguments.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.contracts.resources.get_resource_markets_arguments;
  return proto.koinos.contracts.resources.get_resource_markets_arguments.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.contracts.resources.get_resource_markets_arguments} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.contracts.resources.get_resource_markets_arguments}
 */
proto.koinos.contracts.resources.get_resource_markets_arguments.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.contracts.resources.get_resource_markets_arguments.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.contracts.resources.get_resource_markets_arguments.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.contracts.resources.get_resource_markets_arguments} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.contracts.resources.get_resource_markets_arguments.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.contracts.resources.get_resource_markets_result.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.contracts.resources.get_resource_markets_result.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.contracts.resources.get_resource_markets_result} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.contracts.resources.get_resource_markets_result.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: (f = msg.getValue()) && proto.koinos.contracts.resources.resource_markets.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.contracts.resources.get_resource_markets_result}
 */
proto.koinos.contracts.resources.get_resource_markets_result.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.contracts.resources.get_resource_markets_result;
  return proto.koinos.contracts.resources.get_resource_markets_result.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.contracts.resources.get_resource_markets_result} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.contracts.resources.get_resource_markets_result}
 */
proto.koinos.contracts.resources.get_resource_markets_result.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.koinos.contracts.resources.resource_markets;
      reader.readMessage(value,proto.koinos.contracts.resources.resource_markets.deserializeBinaryFromReader);
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.contracts.resources.get_resource_markets_result.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.contracts.resources.get_resource_markets_result.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.contracts.resources.get_resource_markets_result} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.contracts.resources.get_resource_markets_result.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.koinos.contracts.resources.resource_markets.serializeBinaryToWriter
    );
  }
};


/**
 * optional resource_markets value = 1;
 * @return {?proto.koinos.contracts.resources.resource_markets}
 */
proto.koinos.contracts.resources.get_resource_markets_result.prototype.getValue = function() {
  return /** @type{?proto.koinos.contracts.resources.resource_markets} */ (
    jspb.Message.getWrapperField(this, proto.koinos.contracts.resources.resource_markets, 1));
};


/**
 * @param {?proto.koinos.contracts.resources.resource_markets|undefined} value
 * @return {!proto.koinos.contracts.resources.get_resource_markets_result} returns this
*/
proto.koinos.contracts.resources.get_resource_markets_result.prototype.setValue = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.contracts.resources.get_resource_markets_result} returns this
 */
proto.koinos.contracts.resources.get_resource_markets_result.prototype.clearValue = function() {
  return this.setValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.contracts.resources.get_resource_markets_result.prototype.hasValue = function() {
  return jspb.Message.getField(this, 1) != null;
};


