// source: koinos/rpc/p2p/p2p_rpc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.koinos.rpc.p2p.get_gossip_status_request');
goog.provide('proto.koinos.rpc.p2p.get_gossip_status_response');
goog.provide('proto.koinos.rpc.p2p.p2p_request');
goog.provide('proto.koinos.rpc.p2p.p2p_request.RequestCase');
goog.provide('proto.koinos.rpc.p2p.p2p_response');
goog.provide('proto.koinos.rpc.p2p.p2p_response.ResponseCase');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.koinos.rpc.error_response');
goog.require('proto.koinos.rpc.reserved_rpc');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.rpc.p2p.get_gossip_status_request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.koinos.rpc.p2p.get_gossip_status_request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.rpc.p2p.get_gossip_status_request.displayName = 'proto.koinos.rpc.p2p.get_gossip_status_request';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.rpc.p2p.get_gossip_status_response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.koinos.rpc.p2p.get_gossip_status_response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.rpc.p2p.get_gossip_status_response.displayName = 'proto.koinos.rpc.p2p.get_gossip_status_response';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.rpc.p2p.p2p_request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.koinos.rpc.p2p.p2p_request.oneofGroups_);
};
goog.inherits(proto.koinos.rpc.p2p.p2p_request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.rpc.p2p.p2p_request.displayName = 'proto.koinos.rpc.p2p.p2p_request';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.koinos.rpc.p2p.p2p_response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.koinos.rpc.p2p.p2p_response.oneofGroups_);
};
goog.inherits(proto.koinos.rpc.p2p.p2p_response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.koinos.rpc.p2p.p2p_response.displayName = 'proto.koinos.rpc.p2p.p2p_response';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.rpc.p2p.get_gossip_status_request.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.rpc.p2p.get_gossip_status_request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.rpc.p2p.get_gossip_status_request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.p2p.get_gossip_status_request.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.rpc.p2p.get_gossip_status_request}
 */
proto.koinos.rpc.p2p.get_gossip_status_request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.rpc.p2p.get_gossip_status_request;
  return proto.koinos.rpc.p2p.get_gossip_status_request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.rpc.p2p.get_gossip_status_request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.rpc.p2p.get_gossip_status_request}
 */
proto.koinos.rpc.p2p.get_gossip_status_request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.rpc.p2p.get_gossip_status_request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.rpc.p2p.get_gossip_status_request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.rpc.p2p.get_gossip_status_request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.p2p.get_gossip_status_request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.rpc.p2p.get_gossip_status_response.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.rpc.p2p.get_gossip_status_response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.rpc.p2p.get_gossip_status_response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.p2p.get_gossip_status_response.toObject = function(includeInstance, msg) {
  var f, obj = {
    enabled: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.rpc.p2p.get_gossip_status_response}
 */
proto.koinos.rpc.p2p.get_gossip_status_response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.rpc.p2p.get_gossip_status_response;
  return proto.koinos.rpc.p2p.get_gossip_status_response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.rpc.p2p.get_gossip_status_response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.rpc.p2p.get_gossip_status_response}
 */
proto.koinos.rpc.p2p.get_gossip_status_response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnabled(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.rpc.p2p.get_gossip_status_response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.rpc.p2p.get_gossip_status_response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.rpc.p2p.get_gossip_status_response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.p2p.get_gossip_status_response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnabled();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool enabled = 1;
 * @return {boolean}
 */
proto.koinos.rpc.p2p.get_gossip_status_response.prototype.getEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.koinos.rpc.p2p.get_gossip_status_response} returns this
 */
proto.koinos.rpc.p2p.get_gossip_status_response.prototype.setEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.koinos.rpc.p2p.p2p_request.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.koinos.rpc.p2p.p2p_request.RequestCase = {
  REQUEST_NOT_SET: 0,
  RESERVED: 1,
  GET_GOSSIP_STATUS: 2
};

/**
 * @return {proto.koinos.rpc.p2p.p2p_request.RequestCase}
 */
proto.koinos.rpc.p2p.p2p_request.prototype.getRequestCase = function() {
  return /** @type {proto.koinos.rpc.p2p.p2p_request.RequestCase} */(jspb.Message.computeOneofCase(this, proto.koinos.rpc.p2p.p2p_request.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.rpc.p2p.p2p_request.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.rpc.p2p.p2p_request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.rpc.p2p.p2p_request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.p2p.p2p_request.toObject = function(includeInstance, msg) {
  var f, obj = {
    reserved: (f = msg.getReserved()) && proto.koinos.rpc.reserved_rpc.toObject(includeInstance, f),
    getGossipStatus: (f = msg.getGetGossipStatus()) && proto.koinos.rpc.p2p.get_gossip_status_request.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.rpc.p2p.p2p_request}
 */
proto.koinos.rpc.p2p.p2p_request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.rpc.p2p.p2p_request;
  return proto.koinos.rpc.p2p.p2p_request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.rpc.p2p.p2p_request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.rpc.p2p.p2p_request}
 */
proto.koinos.rpc.p2p.p2p_request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.koinos.rpc.reserved_rpc;
      reader.readMessage(value,proto.koinos.rpc.reserved_rpc.deserializeBinaryFromReader);
      msg.setReserved(value);
      break;
    case 2:
      var value = new proto.koinos.rpc.p2p.get_gossip_status_request;
      reader.readMessage(value,proto.koinos.rpc.p2p.get_gossip_status_request.deserializeBinaryFromReader);
      msg.setGetGossipStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.rpc.p2p.p2p_request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.rpc.p2p.p2p_request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.rpc.p2p.p2p_request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.p2p.p2p_request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReserved();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.koinos.rpc.reserved_rpc.serializeBinaryToWriter
    );
  }
  f = message.getGetGossipStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.koinos.rpc.p2p.get_gossip_status_request.serializeBinaryToWriter
    );
  }
};


/**
 * optional koinos.rpc.reserved_rpc reserved = 1;
 * @return {?proto.koinos.rpc.reserved_rpc}
 */
proto.koinos.rpc.p2p.p2p_request.prototype.getReserved = function() {
  return /** @type{?proto.koinos.rpc.reserved_rpc} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.reserved_rpc, 1));
};


/**
 * @param {?proto.koinos.rpc.reserved_rpc|undefined} value
 * @return {!proto.koinos.rpc.p2p.p2p_request} returns this
*/
proto.koinos.rpc.p2p.p2p_request.prototype.setReserved = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.koinos.rpc.p2p.p2p_request.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.p2p.p2p_request} returns this
 */
proto.koinos.rpc.p2p.p2p_request.prototype.clearReserved = function() {
  return this.setReserved(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.p2p.p2p_request.prototype.hasReserved = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional get_gossip_status_request get_gossip_status = 2;
 * @return {?proto.koinos.rpc.p2p.get_gossip_status_request}
 */
proto.koinos.rpc.p2p.p2p_request.prototype.getGetGossipStatus = function() {
  return /** @type{?proto.koinos.rpc.p2p.get_gossip_status_request} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.p2p.get_gossip_status_request, 2));
};


/**
 * @param {?proto.koinos.rpc.p2p.get_gossip_status_request|undefined} value
 * @return {!proto.koinos.rpc.p2p.p2p_request} returns this
*/
proto.koinos.rpc.p2p.p2p_request.prototype.setGetGossipStatus = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.koinos.rpc.p2p.p2p_request.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.p2p.p2p_request} returns this
 */
proto.koinos.rpc.p2p.p2p_request.prototype.clearGetGossipStatus = function() {
  return this.setGetGossipStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.p2p.p2p_request.prototype.hasGetGossipStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.koinos.rpc.p2p.p2p_response.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.koinos.rpc.p2p.p2p_response.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  RESERVED: 1,
  ERROR: 2,
  GET_GOSSIP_STATUS: 3
};

/**
 * @return {proto.koinos.rpc.p2p.p2p_response.ResponseCase}
 */
proto.koinos.rpc.p2p.p2p_response.prototype.getResponseCase = function() {
  return /** @type {proto.koinos.rpc.p2p.p2p_response.ResponseCase} */(jspb.Message.computeOneofCase(this, proto.koinos.rpc.p2p.p2p_response.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.koinos.rpc.p2p.p2p_response.prototype.toObject = function(opt_includeInstance) {
  return proto.koinos.rpc.p2p.p2p_response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.koinos.rpc.p2p.p2p_response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.p2p.p2p_response.toObject = function(includeInstance, msg) {
  var f, obj = {
    reserved: (f = msg.getReserved()) && proto.koinos.rpc.reserved_rpc.toObject(includeInstance, f),
    error: (f = msg.getError()) && proto.koinos.rpc.error_response.toObject(includeInstance, f),
    getGossipStatus: (f = msg.getGetGossipStatus()) && proto.koinos.rpc.p2p.get_gossip_status_response.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.koinos.rpc.p2p.p2p_response}
 */
proto.koinos.rpc.p2p.p2p_response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.koinos.rpc.p2p.p2p_response;
  return proto.koinos.rpc.p2p.p2p_response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.koinos.rpc.p2p.p2p_response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.koinos.rpc.p2p.p2p_response}
 */
proto.koinos.rpc.p2p.p2p_response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.koinos.rpc.reserved_rpc;
      reader.readMessage(value,proto.koinos.rpc.reserved_rpc.deserializeBinaryFromReader);
      msg.setReserved(value);
      break;
    case 2:
      var value = new proto.koinos.rpc.error_response;
      reader.readMessage(value,proto.koinos.rpc.error_response.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 3:
      var value = new proto.koinos.rpc.p2p.get_gossip_status_response;
      reader.readMessage(value,proto.koinos.rpc.p2p.get_gossip_status_response.deserializeBinaryFromReader);
      msg.setGetGossipStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.koinos.rpc.p2p.p2p_response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.koinos.rpc.p2p.p2p_response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.koinos.rpc.p2p.p2p_response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.koinos.rpc.p2p.p2p_response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReserved();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.koinos.rpc.reserved_rpc.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.koinos.rpc.error_response.serializeBinaryToWriter
    );
  }
  f = message.getGetGossipStatus();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.koinos.rpc.p2p.get_gossip_status_response.serializeBinaryToWriter
    );
  }
};


/**
 * optional koinos.rpc.reserved_rpc reserved = 1;
 * @return {?proto.koinos.rpc.reserved_rpc}
 */
proto.koinos.rpc.p2p.p2p_response.prototype.getReserved = function() {
  return /** @type{?proto.koinos.rpc.reserved_rpc} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.reserved_rpc, 1));
};


/**
 * @param {?proto.koinos.rpc.reserved_rpc|undefined} value
 * @return {!proto.koinos.rpc.p2p.p2p_response} returns this
*/
proto.koinos.rpc.p2p.p2p_response.prototype.setReserved = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.koinos.rpc.p2p.p2p_response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.p2p.p2p_response} returns this
 */
proto.koinos.rpc.p2p.p2p_response.prototype.clearReserved = function() {
  return this.setReserved(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.p2p.p2p_response.prototype.hasReserved = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional koinos.rpc.error_response error = 2;
 * @return {?proto.koinos.rpc.error_response}
 */
proto.koinos.rpc.p2p.p2p_response.prototype.getError = function() {
  return /** @type{?proto.koinos.rpc.error_response} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.error_response, 2));
};


/**
 * @param {?proto.koinos.rpc.error_response|undefined} value
 * @return {!proto.koinos.rpc.p2p.p2p_response} returns this
*/
proto.koinos.rpc.p2p.p2p_response.prototype.setError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.koinos.rpc.p2p.p2p_response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.p2p.p2p_response} returns this
 */
proto.koinos.rpc.p2p.p2p_response.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.p2p.p2p_response.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional get_gossip_status_response get_gossip_status = 3;
 * @return {?proto.koinos.rpc.p2p.get_gossip_status_response}
 */
proto.koinos.rpc.p2p.p2p_response.prototype.getGetGossipStatus = function() {
  return /** @type{?proto.koinos.rpc.p2p.get_gossip_status_response} */ (
    jspb.Message.getWrapperField(this, proto.koinos.rpc.p2p.get_gossip_status_response, 3));
};


/**
 * @param {?proto.koinos.rpc.p2p.get_gossip_status_response|undefined} value
 * @return {!proto.koinos.rpc.p2p.p2p_response} returns this
*/
proto.koinos.rpc.p2p.p2p_response.prototype.setGetGossipStatus = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.koinos.rpc.p2p.p2p_response.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.koinos.rpc.p2p.p2p_response} returns this
 */
proto.koinos.rpc.p2p.p2p_response.prototype.clearGetGossipStatus = function() {
  return this.setGetGossipStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.koinos.rpc.p2p.p2p_response.prototype.hasGetGossipStatus = function() {
  return jspb.Message.getField(this, 3) != null;
};


